### ISSUE TITLE
PC 게임 조사

### ISSUE THREAD

**Issue by kimy0303** [rhakdkdl16/GithubTest#2]
회사
장르
스크린샷
게임엔진
간단한소개

**Comment by rhakdkdl16** [comment]
![Jang_Screenshot](https://user-images.githubusercontent.com/54298426/66635319-e9282200-ec49-11e9-909e-bad9c8e00b50.jpg)
![Jang_Screenshot2](https://user-images.githubusercontent.com/54298426/66635321-e9282200-ec49-11e9-950d-1aafef98b4cd.PNG)
